version: '3'
networks:
  movies:
    driver: bridge
#  default:
#    driver: bridge
services:
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    container_name: movies_webserver
    ports:
      - "8001:80"
    volumes:
      - ./movies_api/:/var/www/movies_api
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/ssl/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - movies
  movies_api:
    container_name: movies_api
    build:
      context: ./movies_api
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/movies_api
    env_file:
      - .env
    volumes:
      - ./movies_api/:/var/www/movies_api
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - movies
  movies_api_db:
    image: mariadb:latest
    restart: unless-stopped
    tty: true
    container_name: movies_api_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: movies_api_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - mysql_data:/var/lib/mysql
#      - ./docker/mysql/movies_api_db:/var/lib/mysql
    networks:
      - movies
volumes:
  mysql_data:




